services:
  nginx1:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/nginx.conf
    networks:
      - mynet

  nginx2:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
    networks:
      - mynet

  nginx3:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx3.conf:/etc/nginx/nginx.conf
    networks:
      - mynet

  app:
    build: ./app
    ports:
      - "8000:5000"
    networks:
      - mynet

networks:
  mynet:
