events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://nginx2;
            proxy_set_header X-Forwarded-For $remote_addr;  # Используем только IP клиента
        }
    }
}